@startuml

title __TOKYOCLIENT's Class Diagram__\n

  namespace TokyoClient {
    class TokyoClient.TokyoClient {
        - botEnabled : boolean
        - sc : Scanner
        + TokyoClient()
        + connectToGame()
        {static} + main()
    }
  }
  

  TokyoClient.TokyoClient o-- TokyoClient.Bot.SimpleBot : simpleBot


right footer


endfooter

@enduml
